config:
  dataset: dsprites
  image_size: 64
  dvae_checkpoint: output/dvae_dsprites/checkpoints/model_500000
  c_dim: 10
  s_dim: 0
  gp_param: 10.0
  info_alpha: 1e-4
  batch_size: 64
  max_iter: 300000
  optimizer: rmsprop
  lr_g: 0.001
  lr_d: 0.0001
  generator:
    name: DVAEGenerator
  disriminator:
    name: DVAEDiscriminator
