config:
  dataset: chairs
  image_size: 64
  dvae_checkpoint: output/dvae_chairs/checkpoints/model_1000000
  c_dim: 20
  s_dim: 256
  gp_param: 1e3
  info_alpha: 1e-4
  batch_size: 64
  max_iter: 300000
  optimizer: rmsprop
  lr_g: 1e-4
  lr_d: 1e-4
  generator:
    name: ResNetGenerator
  discriminator:
    name: ResNetDiscriminator
