config:
  dataset: dsprites
  image_size: 64
  dvae_checkpoint: output/dvae_dsprites/checkpoints/model_500000
  c_dim: 10
  s_dim: 0
  gp_param: 1e1
  info_alpha: 1e-4
  batch_size: 64
  max_iter: 300000
  optimizer: rmsprop
  lr_g: 1e-3
  lr_d: 1e-4
  generator:
    name: DVAEGenerator
  discriminator:
    name: DVAEDiscriminator
